version: "3.8"
services:
  db:
    container_name: my-sequel
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=wallet
      - MYSQL_ROOT_PASSWORD=mickeymouse
      - MYSQL_USER=wallet_user
      - MYSQL_PASSWORD=bohemian
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local
